apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantaerolog
  labels:
    app: quantaerolog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quantaerolog
  template:
    metadata:
      labels:
        app: quantaerolog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: quantaerolog
        image: quantaerolog/prod:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: quantaerolog-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: quantaerolog-secrets
              key: redis-url
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: quantaerolog-config

---
apiVersion: v1
kind: Service
metadata:
  name: quantaerolog
spec:
  selector:
    app: quantaerolog
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quantaerolog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quantaerolog
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 