name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Build and push Production image
      uses: docker/build-push-action@v4
      with:
        context: .
        target: prod
        push: true
        tags: |
          quantaerolog/prod:latest
          quantaerolog/prod:${{ steps.version.outputs.VERSION }}
        cache-from: type=registry,ref=quantaerolog/prod:buildcache
        cache-to: type=registry,ref=quantaerolog/prod:buildcache,mode=max

    - name: Deploy to Production
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo "$KUBE_CONFIG" > kubeconfig.yaml
        kubectl --kubeconfig=kubeconfig.yaml set image deployment/quantaerolog \
          quantaerolog=quantaerolog/prod:${{ steps.version.outputs.VERSION }}
        kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/quantaerolog

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.version.outputs.VERSION }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 